created: false
Player1:
  location:
    world: none
    x: 0
    y: 0
    z: 0
    yaw: 0
    pitch: 0
  id: 0
  valuesSet: false
  Texture: 'eyJ0aW1lc3RhbXAiOjE1NDgwNzU1MjAyOTgsInByb2ZpbGVJZCI6IjUzNTZhY2MyOGVjMzRmZTk5MmUxODQyNzc2OGUxOTIyIiwicHJvZmlsZU5hbWUiOiJNNHhmMHgiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2M2NmJhMDkxZDA4NmIxMTAzMDI5NTg3NDQ5Y2M3ODM2YWQ4ZjYyZTgwMzQwZTE4NjBhMDM0NDg3ZDVlOTFmMjYiLCJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifX19fQ=='
  Signature: 'NxqnYzcOTMWnyze1h2/c/gJ4/b2os4JHV8vf/0qgMNxBmiJpSGs+k6hv4/l6/3m8pSsDUHfF0bdHJFsK8hfPdv7/Z4sOctdc+zzAPZ57RuruRQKvxAqEU/lHW+BLY3m8LiXU8JcId04Y83qX4/k/TbGbnmEtynrPkljHrHxB2pE5aFGniEBnXVmBbbfZR+5iGH5k1rQtUwD1kGmYXT7g9erQu1fGVUzRsTzyk8rCqk0w+wWYro/F4rYuFTMqypp0vCeRsGDzDuSxpgewCZb82OB3Vez165N3Q1rFfA+7utiC7UbDrK6xhQbTJ31T6NVaIMQR4ReWT7tCzY6uY7Wi4Ru/IUuD0HAQNeGpPC4ekuJB6M2oJ7XnfpohQ49cP8Dzek6o4mNqOYp3wvsc8fOtKZwcRgJxo33fT/l+NR+iheEYNA7ZAkqGKkuygdkdWxacZTC2yRFQGkGPEpcaYPyEg3VbDK1DjL8i0P9nAVKKsplIEnKT68JhkCTPwvHrs6Jspdenzm+7FwGkeuACCutE5grtSCCjv/o8w8fxGVi2yDY8LN3UYKKO/fkxjMQTrc6eyDBaUQWC7Vevn0HT/pIt3pBFg1WehG3cKIx2B6pQiObZVriFyEQsLxxcCWk0mpV0mHVhJeEGrqQ+7Msa/fNVQBLO+UQotXR84AE1SuBI6jI='

Player2:
  location:
    world: none
    x: 0
    y: 0
    z: 0
    yaw: 0
    pitch: 0
  id: 0
  valuesSet: false
  Texture: 'eyJ0aW1lc3RhbXAiOjE1NDgwNzg0MDQwNzYsInByb2ZpbGVJZCI6ImI5NzQ1Nzc2ZGQ2MTQ0Nzc4YzAzNDg1MWRhODNiZGZlIiwicHJvZmlsZU5hbWUiOiJNYXJ2Q29kZSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNWZiMGFkY2JjYmMzYzIwNDAxYmE0NTk5M2NmOGYwMmIzYmYyMTVkNjZmOTlkYWEzMjk0ZDdkYTE0NDVjZTM3OSJ9fX0='
  Signature: 'UTu6kl7YmnPOl/ok54/kIgm+PzW/0TKXuIQVzMHrTBGIC3ZQYfuB+Ta2yspnCK8Lsyt/NfNkLNHuSK4OWSmoNeWvUEK/u45JWbwU3o/ukKAXFF4O9ht/tWtqGKwd1V9LsbCMKgM7e/GqclMt3DYzF2h2X0BzVCg4Z6Fj3rqgjY/tGNpHWKbGPDbmEaD1J1HeGUIWpHHmpJJlSpZT43sWRc3PfuE3T+3ELksQSMpYzI1IBaTkwCRVw0Fj/40494Ss7l6N0ag/3CW1tv8fjjDdLWxS7n+Pr0u6jU6pqHIraP8aGAW86EUaDv/nF9SOhpt4NwP9A2HjPuE/oBYjJVb5govfs9icieHBTL/HOoMLl1csqvN6Z8PaQH6A7Z0wmJTfQSE0f7G+bSUYN5XODAxCJL06iB1DFdrhxNZ2gl8T8lumZBDUNpJvO944ctdv3nVHw8DRa3eXnYzF1E7vswFaGCTiInw+sGyWg7q/vRp9/plGa+4x9Lvije/pTVqYdlx5j4L4IKrmg1s1zfrBjG6XW3pm3opGsmgmX35ywMZBS1l9DDOkw7wC7XhAyzeOWC1LqK/up8fwFdNjzlKXqs8Z6gM+i6LLq88JbVV4fMWjuobJsl2coBZr1WkPbbB07gPJpU2GcF6jUJmS8aK9pc/Q/CwWBsxfWkPZBmamkVKYmC8='