Website: http://192.168.178.22/gb
Challenges:
  pw1: 
    password: pw1
    done1: false
    done2: false
    done3: false
  pw2: 
    password: pw2
    done1: false
    done2: false
    done3: false
  pw3: 
    password: pw3
    done1: false
    done2: false
    done3: false
  pw4: 
    password: pw4
    done1: false
    done2: false
    done3: false
  pw5: 
    password: pw5
    done1: false
    done2: false
    done3: false
  pw6: 
    password: pw6
    done1: false
    done2: false
    done3: false
  
Lifes:
  Team1: 3
  Team2: 3
  Team3: 3

Match:
  Active: false 
  Time: 0
   
Deathmatch:
  Active: true
  Build: false
  Time: 0
  
Teams:
  Ready: false
  Red:
    Player1: 'Pl1'
    Player2: 'Pl2'
  Green:
    Player1: 'Pl1'
    Player2: 'Pl2'
  Blue:
    Player1: 'Pl1'
    Player2: 'Pl2'
    
Spawns:
  World: world
  Team1:
    Ready: false 
    x: 50
    y: 50
    z: 50
    yaw: 10
    pitch: 10
  Team2:
    Ready: false
    x: 50
    y: 50
    z: 50
    yaw: 10
    pitch: 10
  Team3:
    Ready: false
    x: 50
    y: 50
    z: 50
    yaw: 10
    pitch: 10
DMSpawns:
  World: world
  Team1:
    Ready: false 
    x: 50
    y: 50
    z: 50
    yaw: 10
    pitch: 10
  Team2:
    Ready: false
    x: 50
    y: 50
    z: 50
    yaw: 10
    pitch: 10
  Team3:
    Ready: false
    x: 50
    y: 50
    z: 50
    yaw: 10
    pitch: 10 
  Middle:
    Ready: false
    x: 50
    y: 50
    z: 50
    yaw: 10
    pitch: 10 